import Head from 'next/head'
import { NextPage } from 'next'



const Products : NextPage =()=> {
  return (
    <>
      <Head>
        <title>Nossos pordutos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque saepe totam quibusdam ducimus 
      hic consequuntur optio nobis sint iure, facere dicta aut ad necessitatibus distinctio eveniet provident soluta illum. Commodi?
        </h1>
      </main>
    </>
  )
}

export default Products